spring.datasource.username=restadmin
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.jpa.database=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Force the database to create the objects
# spring.jpa.hibernate.ddl-auto=update
# hibernate won't  create the database for use instead it will validate it is consistent against the entities.
spring.jpa.hibernate.ddl-auto=validate

# Show SQL queries
spring.jpa.show-sql=true
# Format the SQL
spring.jpa.properties.hibernate.format_sql=true

#Show bind values
logging.level.org.hibernate.orm.jdbc.bind=trace

# hikari parameters - parameters to control the pool of database connections
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.pool-name=RestDB-Pool

# Recommended parameters for production
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.useLocalSessionState=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=true
spring.datasource.hikari.data-source-properties.cacheServerConfiguration=true
spring.datasource.hikari.data-source-properties.elideSetAutoCommits=true
spring.datasource.hikari.data-source-properties.maintainTimeStats=false

# Parameters to do reflection of the entities and creates the sql scripts.

# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-and-create.sql
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=drop-and-create.sql

# Just disable for the moment
# spring.flyway.enabled=false