# es logging.level y luego el nivel dentro del proyecto en donde quieres habilitar el log
# logging.level.guru.springframework.controllers=DEBUG
logging.level.guru.springframework=DEBUG
spring.flyway.enabled=false